### ISSUE TITLE
[Feature]: Add support for private services (`pserv`) type in Render.com

### ISSUE THREAD

**Issue by Lasim** [deploystackio/feedback#10]
### Description

Add support for private services (`pserv`) type in Render.com Infrastructure as Code templates. Currently, all services are set to `web` type by default, which doesn't work for databases and other TCP-based services.

#### Current Behavior

When converting Docker configurations to Render blueprints, all services are assigned `type: web`. This assumes HTTP protocol support, which causes deployment failures for services like:

- MariaDB/MySQL
- Redis
- PostgreSQL
- MongoDB

Example current output for MariaDB:

```yaml
services:
  - name: db
    type: web  # Incorrect - causes deployment failure
    env: docker
    image:
      url: docker.io/library/mariadb:11.2
```

### Suggested Solution

Added configuration-based service type detection that:
1. Uses a JSON configuration file to map Docker images to appropriate Render service types
2. Automatically sets `type: pserv` for TCP-based services
3. Maintains `type: web` as default for HTTP-based services

Example new output for MariaDB:
```yaml
services:
  - name: db
    type: pserv  # Correct - supports TCP protocol
    env: docker
    image:
      url: docker.io/library/mariadb:11.2
```

#### Contributing New Service Types

Users can add support for additional private services by:
1. Opening a pull request to update `service-types.json`
2. Providing the Docker image name and required service type
3. Including a brief description explaining why the service type is needed

This ensures consistent handling of service types across all deployments.
