### ISSUE TITLE
[Feature]: add exclude_providers from IaC generation

### ISSUE THREAD

**Issue by Lasim** [deploystackio/feedback#21]
### Description

Currently, DeployStack generates Infrastructure as Code templates for all supported providers (AWS, Render.com, DigitalOcean) for every branch. However, some applications may need to exclude specific providers for certain branches due to:

- Platform-specific features not available in some versions
- Testing requirements for specific cloud providers
- Resource constraints or compatibility issues
- Cost optimization needs

#### Use Case

Users want to:

- Exclude specific cloud providers from template generation for certain branches
- Maintain different provider support across different versions
- Control which deployment options are available per branch
- Configure provider exclusions through the existing config.yml structure

#### Suggested Solution

Extend the branch configuration in `.deploystack/config.yml` to support provider exclusions:

1. Schema Extension
   ```yaml
   deployment:
     branches:
       v2:
         label: "Beta (v2.x)"
         description: "Preview of v2.x release"
         priority: 1
         exclude_providers:  # New configuration
           - "aws"          # Exclude AWS for this branch
           - "rnd"         # Exclude Render.com for this branch
   ```

2. Configuration Updates
   - Add `exclude_providers` array to branch configuration
   - Support provider codes: "aws" (AWS), "rnd" (Render), "dop" (DigitalOcean)
   - Update JSON schema to validate provider codes
   - Make the exclusion list optional for backward compatibility

3. Implementation Details
   - Update template generation logic to check exclusions
   - Skip template generation for excluded providers
   - Update deployment button generation to respect exclusions
   - Add validation for provider codes

#### Technical Considerations

1. Schema Updates
   ```json
   {
     "exclude_providers": {
       "type": "array",
       "description": "List of providers to exclude from template generation",
       "items": {
         "type": "string",
         "enum": ["aws", "rnd", "dop"],
         "description": "Provider code to exclude"
       },
       "uniqueItems": true
     }
   }
   ```

2. Backend Changes
   - Modify template generation pipeline
   - Update provider availability checks
   - Add exclusion validation logic
   - Update deployment button generation

#### Benefits

1. For Users:
   - Fine-grained control over provider support
   - Branch-specific provider configuration
   - Clear documentation of provider limitations
   - Simplified maintenance of multi-version applications

2. For DeployStack:
   - Reduced unnecessary template generation
   - Better support for diverse application needs
   - More flexible configuration options
   - Improved user experience
